# Generated by Django 3.2 on 2021-11-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=500)),
                ('proj_status', models.CharField(blank=True, max_length=500)),
                ('proj_starting_date', models.CharField(blank=True, max_length=500)),
                ('proj_last_updated', models.CharField(blank=True, max_length=500)),
                ('proj_bussiness_person_involved', models.CharField(blank=True, max_length=500)),
                ('proj_developers_involved', models.CharField(blank=True, max_length=500)),
                ('proj_url', models.CharField(blank=True, max_length=500)),
                ('proj_remarks', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeaturesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=500)),
                ('Features', models.CharField(blank=True, max_length=500)),
                ('Phase', models.CharField(blank=True, max_length=500)),
                ('Description', models.CharField(blank=True, max_length=500)),
                ('Status', models.CharField(blank=True, max_length=500)),
                ('UAT_status', models.CharField(blank=True, max_length=500)),
                ('UAT_done_by', models.CharField(blank=True, max_length=500)),
                ('Person_assigned', models.CharField(blank=True, max_length=500)),
                ('Any_Comments', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
