# Generated by Django 3.2 on 2021-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=500)),
                ('resource_name', models.CharField(blank=True, max_length=500)),
                ('skill', models.CharField(blank=True, max_length=500)),
                ('actual_hours', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(blank=True, max_length=500)),
                ('work_details', models.CharField(blank=True, max_length=500)),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('clients', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
